### ISSUE TITLE
In-app updates disabled

### ISSUE THREAD

**Issue by KZawWin** [microsoft/appcenter-sdk-android#1377]
We pushed the new version with mandatory update. When we re-launched the new version, the attached dialogue is popped up. 

![Screenshot_20200309-101120_InTouch](https://user-images.githubusercontent.com/61959578/76185155-f0edf180-61fc-11ea-8e85-7c8ecb94eb98.jpg)

When we choose to ignore, the dialogue dismissed. When we relaunch it redirected to browser and asked to log in.
![image](https://user-images.githubusercontent.com/61959578/76185337-61950e00-61fd-11ea-82dc-74204d9a988b.png)

When we choose to "Reinstall app", it redirected to browser and showed the following error.
![Screenshot_20200307-154518_Chrome](https://user-images.githubusercontent.com/61959578/76185411-87baae00-61fd-11ea-9cf3-9a9fc383bf8d.jpg)

We would like to know that do we need to set any settings inside the appcenter or what should we add additional code to handle this issue.

1. Which SDK version are you using?
    - 2.4.1
2. Which OS version did you experience the issue on?
    - Android 9
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Samsung S9+

Thanks for your answer in advanced.

**Comment by guperrot** [comment]
Hi, the current versionCode and versionName of the android build must be published in a distribution group on the portal for your application, otherwise you will get that sideloaded error.

It's also recommended to update SDK version to 3.0.0 as we no longer require opening the browser for public distribution groups (still required for private groups, see 3.0.0 docs at https://docs.microsoft.com/en-us/appcenter/sdk/distribute/android#use-private-distribution-group).

**Comment by annakocheshkova** [comment]
Hi there, is there anything else we can help you with? I'm closing this one, feel free to re-open if you need anything.
