### ISSUE TITLE
Add recommended Progaurd rules to your SDK documentation

### ISSUE THREAD

**Issue by noobdev19** [microsoft/appcenter-sdk-android#1420]
**Is your feature request related to a problem? Please describe.**
Your guides for the SDK have no documentations for progaurd. If you use progaurd with minify enabled the SDK does not send any data.

**Describe the solution you'd like**
Please add recommended progaurd rules to make your SDK work. Add minifyEnabled true in your sample android app gradle file along with progaurd rules that can be downloaded and tested.

**Describe alternatives you've considered**
Tried adding
-keep class com.microsoft.appcenter.** { *; }
-keep interface com.microsoft.appcenter.** { *; }
But it simply does not work. A developer should not have to play guessing game with this.

**Additional context**
Take a look at EventBus library documentation. They clearly mention what progaurd rules must be added to client apps for this library to work.
https://github.com/greenrobot/EventBus#r8-proguard

**Comment by russelarms** [comment]
Hi, thanks for reaching out!

AppCenter SDK has embedded proguard rules that are used by R8/Proguard so normally you don't have to configure it on application side:
https://github.com/microsoft/appcenter-sdk-android/blob/develop/sdk/appcenter/proguard-rules.pro
https://github.com/microsoft/appcenter-sdk-android/blob/develop/sdk/appcenter-push/proguard-rules.pro
https://github.com/microsoft/appcenter-sdk-android/blob/develop/sdk/appcenter-crashes/proguard-rules.pro
https://github.com/microsoft/appcenter-sdk-android/blob/develop/sdk/appcenter-analytics/proguard-rules.pro
https://github.com/microsoft/appcenter-sdk-android/blob/develop/sdk/appcenter-distribute/proguard-rules.pro

There are some additional steps for a proper deobfuscation on the portal: https://docs.microsoft.com/en-us/appcenter/diagnostics/android-deobfuscation
But, SDK works fine with `minifyEnabled true` out of the box.

I've checked a minified apk and everything works smoothly for me.
Could you open a new issue with the _Problem report_ template and include all the information in the template? Otherwise, it's difficult for us to test your exact scenario.
