### ISSUE TITLE
Host artifact elsewhere - JCenter is shutting down on May

### ISSUE THREAD

**Issue by alvindizon** [microsoft/appcenter-sdk-android#1503]
See this article for details: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by russelarms** [comment]
Hi @alvindizon, thanks for bringing this to our attention! We will look at how and where to go from JCenter.

**Comment by farkerhaiku** [comment]
Is there any information on when this issue will be resolved and where you are moving to?

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for getting in touch with us! We are working on it. We are notify you when the issue will be resolved.

**Comment by AnastasiaKubova** [comment]
Hi there! Due to the termination of `jCenter` support all our assemblies were moved to the `Maven Central` repository. Please pay attention that the `Maven Centra` doesn't contain deprecated modules. 

See more about migration to `Maven Central` [here](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/android#3-add-the-app-center-sdk-modules).
