### ISSUE TITLE
Allow specifying a custom Http Client

### ISSUE THREAD

**Issue by James-Aidoo** [microsoft/appcenter-sdk-android#1545]
We have apps that are supposed to run on Android versions below 5.0 (Appcenter supports 5.0 and above; but you know that already). It would be really great if you would allow users of the sdk to set a custom http client (like OkHttpClient) on which we could enable Tls on Android versions below 5.0 to fix certificate issues. Hopefully, if this is the reason the SDK supports only android versions from 5.0 and above, this feature would remove that blocker.

**Comment by AnastasiaKubova** [comment]
The Android API level was bumped to 21 in the [4.0.0 version](https://github.com/microsoft/appcenter-sdk-android/blob/develop/CHANGELOG.md#app-center-2) of App Center SDK because the root certificate authority of our App Center SSL (`DigiCert Global Root G2`) is unknown in `Android 4.x.` and it can't perform any calls to the backend from the SDK. 
Unfortunately, I am not sure that any `HTTPS` calls (including calls from the SDK) would correct work on `Android 4.x.` because of the certificate issue.

**Comment by James-Aidoo** [comment]
Thanks for getting back to me.
What version of the AppCenter SDK has support for `Android 4.x.`. We may have to downgrade to that or convince management to change the minimum supported Android version of our app.

**Comment by James-Aidoo** [comment]
> What latest version of the AppCenter SDK has support for `Android 4.x.`. We may have to downgrade to that or convince management to change the minimum supported Android version of our app.

I just found the version to `3.3.1`. Thanks.

**Comment by AnastasiaKubova** [comment]
Yes, you are right. But as I mentioned above due to the certificate issue on `Android 4.x` it will not work correctly on `3.3.1` version of App Center SDK.

**Comment by James-Aidoo** [comment]
I guess we have only one option then. Thank you.

**Comment by AnastasiaKubova** [comment]
Okay, then I’m closing this issue but feel free to reopen this issue if you have additional questions.

**Comment by James-Aidoo** [comment]
Sure.
