### ISSUE TITLE
crashes "com.google.firebase.iid.zzc.run" when app starts

### ISSUE THREAD

**Issue by nbsoftware** [Microsoft/AppCenter-SDK-Android#620]
Please see https://github.com/xamarin/GooglePlayServicesComponents/issues/88

Didn't get that until I integrated push notifications for one, and didn't get them either until I updated the packages to 1.3.0, for two. Hence me posting here.

Will recheck with 1.2.0.

And for me, crashes are not random. On my Nexus 5X device it happens all the time, meaning app won't start... ever. Just keeps crashing. Ooops

Damn, was just about to release...

**Comment by MatkovIvan** [comment]
Hi,

Thanks for getting in touch!
According to the context, this is due to [AppCenter DotNet SDK](https://github.com/Microsoft/AppCenter-SDK-DotNet), right?
Please note, the Firebase SDK is no longer a dependency of the App Center SDK. If you wish to **only** use App Center Push service, you can choose to remove the firebase dependencies.
See details here: [How to remove Firebase SDK dependencies](https://docs.microsoft.com/en-us/appcenter/sdk/push/migration/xamarin-android)

I've tested AppCenter Push SDK 1.3.0 **with** Firebase 60.1142.0 on the Nexus 5X with Android 8.1 and it runs without any issue.
Please provide your nuget packages config and verbose log from the device so that we could reproduce this and figure out the root cause of the issue.

Best,
Ivan

**Comment by nbsoftware** [comment]
Hello,

Thanks for your reply.

I've finally figured out that it was because of a device connectivity issue (my test Nexus 5X was registered on an old no longer existent WiFi network).

Once setup correctly, no more crashes.

Worth to mention, my Nexus does not have any SIM card in it.

Then I tried to reproduce the issue by disabling the WiFi, forgetting the known network, etc... to no available: impossible to reproduce the crash.

That being said, I will try to remove the Firebase dependencies and test again.

You can close the issue if you want.

Thanks again.
Fred

**Comment by guperrot** [comment]
Hi, ok and thanks for the feedback.
If you experience another issue, please create the issue on https://github.com/Microsoft/AppCenter-SDK-DotNet.
