### ISSUE TITLE
out of memory errors

### ISSUE THREAD

**Issue by MrLoh** [Microsoft/AppCenter-SDK-Android#900]
### **Description**

One of the most common errors I see in AppCenter on my android react-native project is the following: 

```
com.microsoft.appcenter.crashes.Crashes.saveUncaughtException Crashes.java, line 923
java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw OutOfMemoryError; no stack trace available
```

It seems that the real error report isn't transmitted, because AppCenter Crashes crashes itself, before being able to transmit the error. 

### **Details**

I have no idea how to reproduce this. I am using appcenter-crashes@^1.6.0 for react native.

**Comment by ElektrojungeMS** [comment]
Hey @MrLoh,

Thanks for getting in touch. So here's what happens: your app is using a lot of memory which causes an OOM (out of memory exception). The App Center SDK is catching that exception but since the app is already so low on memory that it received the OOM thus, the App Center SDK doesn't have enough memory to process and throws an OOM itself. (Think of it as OOM-ception if you will ;))
The bottom line is that it's not the App Center SDK itself that is crashing but the issue lies in the memory usage by the app.

My suggestion at this time would be to monitor your app over a long period using https://developer.android.com/topic/performance/memory and maybe try to send events in the app so that they appear on the crash events tab to get some hints as to what the user is doing prior to running out of memory.
Another workaround would be to increase the size of the heap as described in https://developer.android.com/guide/topics/manifest/application-element#largeHeap but this is more like a band aid that won't fix the underlying memory issue.

Finally, you are mentioning that you are using version 1.6.0 of the App Center SDK. It's always a good idea to upgrade to 1.10.0 as described in [our documentation](https://docs.microsoft.com/en-us/appcenter/sdk/troubleshooting/react-native#how-to-update-react-native-sdk-to-the-latest-version).

Best,
Benjamin

**Comment by MrLoh** [comment]
Hi @ElektrojungeMS thanks for the explanation, that pretty much clears up my confusion and confirms my suspicions as to what might be happening. Thanks a lot.

**Comment by ElektrojungeMS** [comment]
You are welcome!
I wish there is more that I could have done. It's one of those cases where a crash reporting tool can only do so much.

Thanks for using App Center and please don't hesitate to get in touch again if anything comes up!
