### ISSUE TITLE
deserialization 

### ISSUE THREAD

**Issue by 360CodeSafe** [Microsoft/AppCenter-SDK-Android#988]
### **Description**
HI！
I am a member of the 360 Code Security Team and found  an Insecure deserialization vulnerability in Buck in our Open Source Detection Project.Details are as follows：

### **Details**
The contents of the file are read in the readObject method of FileManager.java, and the deserialization operation is performed directly at line 162. The attacker may provide a malicious file or write a specific poc to the file for attack (I am not sure Whether the file is controllable).

![default](https://user-images.githubusercontent.com/39950310/53948061-facca880-4101-11e9-9c6c-374c30b387a8.png)

**Comment by achocron** [comment]
Hi there- only the application itself is able to save files to the location that the SDK is reading from, so unless the application exposes a vulnerability for an attacker to save files there, it is probably not easily exploitable. Further, as of today, this method is only used to serialize a `Throwable` upon crashing so that it can be examined when the application is restarted.
